# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-23 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('title', models.TextField(max_length=1000)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'collect',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Footprint1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_content', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'footprint1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Footprint2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('title', models.TextField(max_length=1000)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'footprint2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('sex', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='footprint2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='footprint1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.User'),
        ),
    ]
